import type { FamilyTreeSnapshot } from "@/lib/family-tree/types";

export const demoTree: FamilyTreeSnapshot = {
  id: "descent-demo",
  name: "Descent",
  description:
    "Explore lineage, understand relationship paths, and maintain one shared family record with controlled editing.",
  currentViewerPersonId: "me",
  selectedPersonId: "zhe-gong",
  viewerRole: "guest",
  people: [
    {
      id: "zu-gao-zu",
      primaryName: "Tan Cheng Huat",
      chineseTitle: "太公",
      englishTitle: "Great-grandfather branch root",
      branch: "Root line",
      years: "1908 - 1986",
      x: 80,
      y: 56,
      accent: "blood",
    },
    {
      id: "zu-po",
      primaryName: "Lim Siew Lan",
      chineseTitle: "太婆",
      englishTitle: "Great-grandmother",
      branch: "Root line",
      years: "1912 - 1992",
      x: 330,
      y: 56,
      accent: "marriage",
    },
    {
      id: "gong-gong",
      primaryName: "Tan Boon Kiat",
      chineseTitle: "公公",
      englishTitle: "Grandfather",
      branch: "Eldest son branch",
      years: "1938 - 2019",
      x: 206,
      y: 196,
      accent: "blood",
    },
    {
      id: "zhe-gong",
      primaryName: "Tan Boon Seng",
      chineseTitle: "叔公",
      englishTitle: "Grandfather's younger brother",
      branch: "Second son branch",
      years: "1944 -",
      x: 520,
      y: 196,
      accent: "blood",
    },
    {
      id: "father",
      primaryName: "Tan Wei Ming",
      chineseTitle: "爸爸",
      englishTitle: "Father",
      branch: "Immediate family",
      years: "1973 -",
      x: 206,
      y: 336,
      accent: "blood",
    },
    {
      id: "mother",
      primaryName: "Lee Hui Xin",
      chineseTitle: "妈妈",
      englishTitle: "Mother",
      branch: "Immediate family",
      years: "1976 -",
      x: 456,
      y: 336,
      accent: "marriage",
    },
    {
      id: "me",
      primaryName: "You",
      chineseTitle: "我",
      englishTitle: "Current viewer",
      branch: "Immediate family",
      years: "2001 -",
      x: 206,
      y: 476,
      accent: "blood",
    },
    {
      id: "sister",
      primaryName: "Tan Jia En",
      chineseTitle: "姐姐",
      englishTitle: "Older sister",
      branch: "Immediate family",
      years: "1998 -",
      x: 456,
      y: 476,
      accent: "blood",
    },
    {
      id: "step-brother",
      primaryName: "Ryan Lee",
      chineseTitle: "继兄",
      englishTitle: "Step-brother",
      branch: "Extended family",
      years: "2004 -",
      x: 706,
      y: 476,
      accent: "step",
    },
  ],
  relationships: [
    {
      id: "c1",
      fromPersonId: "zu-gao-zu",
      toPersonId: "zu-po",
      type: "spouse",
      status: "active",
      style: "marriage",
    },
    {
      id: "c2",
      fromPersonId: "zu-gao-zu",
      toPersonId: "gong-gong",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c3",
      fromPersonId: "zu-po",
      toPersonId: "gong-gong",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c4",
      fromPersonId: "zu-gao-zu",
      toPersonId: "zhe-gong",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c5",
      fromPersonId: "zu-po",
      toPersonId: "zhe-gong",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c6",
      fromPersonId: "gong-gong",
      toPersonId: "father",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c7",
      fromPersonId: "father",
      toPersonId: "mother",
      type: "spouse",
      status: "active",
      style: "marriage",
    },
    {
      id: "c8",
      fromPersonId: "father",
      toPersonId: "me",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c9",
      fromPersonId: "mother",
      toPersonId: "me",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c10",
      fromPersonId: "father",
      toPersonId: "sister",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c11",
      fromPersonId: "mother",
      toPersonId: "sister",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "c12",
      fromPersonId: "mother",
      toPersonId: "step-brother",
      type: "step_parent",
      status: "inactive",
      style: "indirect",
    },
  ],
  suggestions: [
    { id: "s1", label: "Add daughter for Tan Jia En", status: "pending" },
    { id: "s2", label: "Correct title for Ryan Lee", status: "pending" },
    {
      id: "s3",
      label: "Mark spouse relationship as divorced",
      status: "pending",
    },
  ],
  activity: [
    {
      id: "a1",
      summary: "Mei Lin approved one suggestion",
      occurredAtLabel: "3m ago",
    },
    {
      id: "a2",
      summary: "Guest link created for Lee branch",
      occurredAtLabel: "16m ago",
    },
    {
      id: "a3",
      summary: "Chinese title override added",
      occurredAtLabel: "1h ago",
    },
  ],
  stats: {
    peopleCount: 412,
    pendingSuggestionCount: 36,
    editorCount: 9,
    liveSync: true,
  },
};
