import { deriveFamilyUnits } from "@/lib/family-tree/family-units";
import type { FamilyTreeSnapshot } from "@/lib/family-tree/types";

const baseDemoTree: Omit<FamilyTreeSnapshot, "familyUnits"> = {
  id: "descent-demo",
  name: "Descent",
  description:
    "Explore lineage, understand relationship paths, and maintain one shared family record with controlled editing.",
  currentViewerPersonId: "viewer",
  selectedPersonId: "grandfather",
  viewerRole: "guest",
  people: [
    {
      id: "grandfather",
      primaryName: "Tan Boon Kiat",
      chineseTitle: "公公",
      englishTitle: "Grandfather",
      relationLabel: "Grandfather",
      branch: "Generation 0",
      years: "1941 - 2019",
      photoUrl: null,
      avatarLabel: "TB",
      description:
        "Paternal grandfather whose records anchor the older branch of the tree.",
      personalNote: "Known for keeping paper family records and old reunion photos.",
      x: 170,
      y: 76,
      accent: "blood",
    },
    {
      id: "grandmother",
      primaryName: "Lim Siew Lan",
      chineseTitle: "奶奶",
      englishTitle: "Grandmother",
      relationLabel: "Grandmother",
      branch: "Generation 0",
      years: "1944 - 2021",
      photoUrl: null,
      avatarLabel: "LS",
      description:
        "Paternal grandmother connected to the same root line through marriage.",
      personalNote: "Her recipes are the easiest way for younger relatives to place her.",
      x: 420,
      y: 76,
      accent: "blood",
    },
    {
      id: "father",
      primaryName: "Daniel Tan",
      chineseTitle: "爸爸",
      englishTitle: "Father",
      relationLabel: "Father",
      branch: "Generation 1",
      years: "1972 -",
      photoUrl: null,
      avatarLabel: "DT",
      description:
        "Alex's father and the main link between the grandparent generation and the immediate family branch.",
      personalNote: "Usually the one who can explain how different cousins connect.",
      x: 170,
      y: 236,
      accent: "blood",
    },
    {
      id: "mother",
      primaryName: "Mei Chen",
      chineseTitle: "妈妈",
      englishTitle: "Mother",
      relationLabel: "Mother",
      branch: "Generation 1",
      years: "1974 -",
      photoUrl: null,
      avatarLabel: "MC",
      description:
        "Alex's mother and the second parent in the immediate family household.",
      personalNote: "Best remembered by younger relatives through holiday planning notes.",
      x: 420,
      y: 236,
      accent: "blood",
    },
    {
      id: "viewer",
      primaryName: "Alex Tan",
      chineseTitle: "我",
      englishTitle: "Current viewer",
      relationLabel: "You",
      branch: "Generation 2",
      years: "2001 -",
      photoUrl: null,
      avatarLabel: "AT",
      description:
        "Current viewer node used as the kinship reference point for relationship labels.",
      personalNote: "Use this node as the baseline when checking whether live kinship labels read correctly.",
      x: 430,
      y: 396,
      accent: "blood",
    },
    {
      id: "spouse",
      primaryName: "Rachel Lee",
      chineseTitle: "妻子",
      englishTitle: "Partner",
      relationLabel: "Partner",
      branch: "Generation 2",
      years: "1999 -",
      photoUrl: null,
      avatarLabel: "RL",
      description:
        "Alex's active partner, used as the primary branch for biological, adoptive, and step-child demo coverage.",
      personalNote: "Helpful seed node for testing spouse labels and shared child connectors.",
      x: 710,
      y: 396,
      accent: "marriage",
    },
    {
      id: "second_partner",
      primaryName: "Morgan Diaz",
      chineseTitle: "Partner",
      englishTitle: "Partner",
      relationLabel: "Partner",
      branch: "Generation 2",
      years: "2000 -",
      photoUrl: null,
      avatarLabel: "MD",
      description:
        "Alex's second active partner, included to prove one person can anchor multiple current partner units.",
      personalNote: "Useful for validating that active partner units stay separate and child placement remains explicit.",
      x: 1020,
      y: 396,
      accent: "marriage",
    },
    {
      id: "former_partner",
      primaryName: "Jamie Park",
      chineseTitle: "Former partner",
      englishTitle: "Former partner",
      relationLabel: "Former partner",
      branch: "Generation 2",
      years: "2000 -",
      photoUrl: null,
      avatarLabel: "JP",
      description:
        "Alex's divorced former partner, retained to keep shared-child history attached to a former family unit.",
      personalNote: "This branch exists to make sure former spouse edges still derive renderable units.",
      x: 140,
      y: 396,
      accent: "marriage",
    },
    {
      id: "sister",
      primaryName: "Grace Tan",
      chineseTitle: "姐姐",
      englishTitle: "Older sister",
      relationLabel: "Older sister",
      branch: "Generation 2",
      years: "1998 -",
      photoUrl: null,
      avatarLabel: "GT",
      description:
        "Alex's older sister, kept on the same generation row but outside the spouse-child cluster.",
      personalNote: "A good visual check that siblings do not get mistaken for spouses.",
      x: 1320,
      y: 396,
      accent: "blood",
    },
    {
      id: "child",
      primaryName: "Chloe Tan",
      chineseTitle: "女儿",
      englishTitle: "Daughter",
      relationLabel: "Daughter",
      branch: "Generation 3",
      years: "2024 -",
      photoUrl: null,
      avatarLabel: "CT",
      description:
        "Child of Alex and Rachel, centered below the marriage pair to make descent direction obvious.",
      personalNote: "This node exists mainly to prove the child connector reads correctly.",
      x: 520,
      y: 556,
      accent: "blood",
    },
    {
      id: "former_child",
      primaryName: "Noah Tan-Park",
      chineseTitle: "Son",
      englishTitle: "Son",
      relationLabel: "Son",
      branch: "Generation 3",
      years: "2020 -",
      photoUrl: null,
      avatarLabel: "NP",
      description:
        "Shared child of Alex and Jamie, used to keep a divorced partner unit populated.",
      personalNote: "Confirms former partner branches still carry primary parent links for shared children.",
      x: 230,
      y: 556,
      accent: "blood",
    },
    {
      id: "adopted_child",
      primaryName: "Mia Tan-Lee",
      chineseTitle: "Daughter",
      englishTitle: "Adopted daughter",
      relationLabel: "Adopted daughter",
      branch: "Generation 3",
      years: "2022 -",
      photoUrl: null,
      avatarLabel: "ML",
      description:
        "Adoptive child of Alex and Rachel, included to verify adoptive edges classify correctly inside a partner unit.",
      personalNote: "This node should derive as adopted without needing any biological parent edge.",
      x: 770,
      y: 556,
      accent: "blood",
    },
    {
      id: "step_child",
      primaryName: "Evan Lee",
      chineseTitle: "Stepchild",
      englishTitle: "Step-son",
      relationLabel: "Step-son",
      branch: "Generation 3",
      years: "2018 -",
      photoUrl: null,
      avatarLabel: "EL",
      description:
        "Rachel's biological child with an explicit step-parent edge from Alex so the step-child branch is intentional.",
      personalNote: "Validates that step-child placement requires both a primary parent and a matching step-parent edge.",
      x: 640,
      y: 836,
      accent: "step",
    },
    {
      id: "guardian_child",
      primaryName: "Samir Khan",
      chineseTitle: "Ward",
      englishTitle: "Ward",
      relationLabel: "Ward",
      branch: "Generation 3",
      years: "2016 -",
      photoUrl: null,
      avatarLabel: "SK",
      description:
        "Child connected to Alex and Morgan through guardian edges to exercise guardian-based family placement.",
      personalNote: "This branch should derive as a guardian child on Alex and Morgan's partner unit.",
      x: 1110,
      y: 556,
      accent: "blood",
    },
  ],
  relationships: [
    {
      id: "r1",
      fromPersonId: "grandfather",
      toPersonId: "grandmother",
      type: "spouse",
      status: "active",
      style: "marriage",
    },
    {
      id: "r2",
      fromPersonId: "grandfather",
      toPersonId: "father",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r3",
      fromPersonId: "grandmother",
      toPersonId: "father",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r4",
      fromPersonId: "father",
      toPersonId: "mother",
      type: "spouse",
      status: "active",
      style: "marriage",
    },
    {
      id: "r5",
      fromPersonId: "father",
      toPersonId: "viewer",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r6",
      fromPersonId: "mother",
      toPersonId: "viewer",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r7",
      fromPersonId: "father",
      toPersonId: "sister",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r8",
      fromPersonId: "mother",
      toPersonId: "sister",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r9",
      fromPersonId: "viewer",
      toPersonId: "spouse",
      type: "spouse",
      status: "active",
      style: "marriage",
    },
    {
      id: "r10",
      fromPersonId: "viewer",
      toPersonId: "child",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r11",
      fromPersonId: "spouse",
      toPersonId: "child",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r12",
      fromPersonId: "viewer",
      toPersonId: "second_partner",
      type: "spouse",
      status: "active",
      style: "marriage",
    },
    {
      id: "r13",
      fromPersonId: "viewer",
      toPersonId: "former_partner",
      type: "spouse",
      status: "divorced",
      style: "marriage",
    },
    {
      id: "r14",
      fromPersonId: "viewer",
      toPersonId: "former_child",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r15",
      fromPersonId: "former_partner",
      toPersonId: "former_child",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r16",
      fromPersonId: "viewer",
      toPersonId: "adopted_child",
      type: "adoptive_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r17",
      fromPersonId: "spouse",
      toPersonId: "adopted_child",
      type: "adoptive_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r18",
      fromPersonId: "spouse",
      toPersonId: "step_child",
      type: "biological_parent",
      status: "active",
      style: "blood",
    },
    {
      id: "r19",
      fromPersonId: "viewer",
      toPersonId: "step_child",
      type: "step_parent",
      status: "active",
      style: "indirect",
    },
    {
      id: "r20",
      fromPersonId: "viewer",
      toPersonId: "guardian_child",
      type: "guardian",
      status: "active",
      style: "blood",
    },
    {
      id: "r21",
      fromPersonId: "second_partner",
      toPersonId: "guardian_child",
      type: "guardian",
      status: "active",
      style: "blood",
    },
  ],
  suggestions: [
    { id: "s1", label: "Add birth place for Chloe Tan", status: "pending" },
    { id: "s2", label: "Correct title for Grace Tan", status: "pending" },
    {
      id: "s3",
      label: "Add photo for Tan Boon Kiat",
      status: "pending",
    },
  ],
  activity: [
    {
      id: "a1",
      summary: "Mei Lin approved one suggestion",
      occurredAtLabel: "3m ago",
    },
    {
      id: "a2",
      summary: "Shared child connector reviewed for Alex branch",
      occurredAtLabel: "16m ago",
    },
    {
      id: "a3",
      summary: "Chinese title override added",
      occurredAtLabel: "1h ago",
    },
  ],
  stats: {
    peopleCount: 412,
    pendingSuggestionCount: 36,
    editorCount: 9,
    liveSync: true,
  },
};

export const demoTree: FamilyTreeSnapshot = {
  ...baseDemoTree,
  familyUnits: deriveFamilyUnits(baseDemoTree.relationships),
};
